### PR TITLE
Add new data onboarding codes.

### PR DESCRIPTION
**Pull request by mvarfima**
The data covers those used by the ECB in their risk indicators: flood and coastal depth, wind speed, fire fiw probs, water stress categories, landslides and subsidence susceptabilities.

### CODE REVIEW

**Comment by joemoorhouse** [comment]
Hi @mvarfima,
As discussed, I looked into a version of the code that uses the full resolution. I added this directly to main branch to server as a template:
https://github.com/os-climate/hazard/blob/main/src/hazard/onboard/tudelft_flood.py
Actually this was a bit interesting because the original data is EPSG 3035. We want to avoid having to reproject so I added the support of arbitrary CRS into physrisk. This simplifies the process: we can keep the data as EPSG 3035 now.
The code works on my laptop with 8 GB RAM but we can also run on say 32 GB machine if needed.
I also refactored a bit.
- I removed from the constructor anything about buckets. We can use an AbstractFileSystem to make the class fairly agnostic to the storage used for the inputs (i.e. S3 / local file system).
- I implemented same run_single pattern as other cases. Here we can use any target that implements ReadWriteDataArray such as OscZarr. See https://github.com/os-climate/hazard/blob/main/src/test/test_onboarding.py test_onboard_tudelft for how to use (best to use tests for the scripts I think).
- I also defined batch_items similar to other cases (inheriting from IndicatorModel[BatchItem]), again a bit of standardisation, bringing into line with other classes.
- That's about it. I note that we need to change the tile creation for maps a bit to deal efficiently with non-global data sets. I'll have a think about that!

Please check if you agree with the pattern - is this good for the other data sets?

Thanks,
Joe

**Comment by mvarfima** [comment]
Hi @joemoorhouse 

the changes look nice. The new pattern is very good and the new free CRS feature is great. I will extend this pattern to the rest of the onboarding codes and add a piece of code for testing for each of them.

Thanks a lot,
Manuel

**Comment by mvarfima** [comment]
Hi @joemoorhouse 

I have pushed the onboarding codes following the code practices suggested: duck typing, batch_items method, prepare method, run single method...

I added a testing function for every script. 

Can you take a look at them to move the merge request forward? 

Thanks,
Manuel

**Comment by joemoorhouse** [comment]
Hi @mvarfima, 

I have finally managed to complete my actions to allow us to fully on-board the data sets and you will see the flood set is now pushed to the Prod bucket with the maps fully generated. 
https://physrisk-ui-sandbox.apps.odh-cl1.apps.os-climate.org/

So we should be good to go with the others now!

I also updated the tudelft_flood.py with how to generate the maps.
 
I've also moved hazard to pdm and I added more checks and linting so we are in a much better shape CI-wise.

So I think next step is to pull in the other sets and we can then generate the maps for those too.

There is a small conflict to resolve and presumably we'll need to run linting to ensure the checks pass. Do you want to do that, or shall I (or indeed would a walk-through be helpful?).

Thanks,
Joe

**Comment by mvarfima** [comment]
redone in #108

**Pull request closed without merging**
