### PR TITLE
Development Seed additions (UKCP18 + Linting)

### PR DESCRIPTION
**Pull request by ciaransweet**
# What this PR is

This PR brings in the changes we've been working on within the Development Seed fork of the repository

I appreciate this is a big change, I wasn't sure when we were looking to re-contribute back, sorry about that!

At a high level, this change:

* Introduces `src/hazard/sources/ukcp18.py` as a new dataset to be used as a source
* Fixes various linting issues that seemed to cause builds to fail, `pdm run all` now passes for me
* Adds the ability to pass in an optional AWS SSO Token for authentication (Some organisations require this)

This has been discussed here: https://github.com/developmentseed/os-climate-hazard/pull/8#issuecomment-2267744603

Happy to jump on a call to run through anything if this makes it easier. Figured I'd rather get these in before the horse really has bolted too far!

### CODE REVIEW

**Comment by ciaransweet** [comment]
@joemoorhouse I think there's a clash between `ruff` + `black`, ruff says there's formatting issues, then it fixes them, then black say's there's issues, then the cycle repeats.

I think it's best to pick one or the other rather than both in tandem, as they'll inevitably clash

**Comment by joemoorhouse** [comment]
Thanks @ciaransweet

Hi @ModeSevenIndustrialSolutions, I think you are happy for OSC to move to ruff and in fact we are doing that in physrisk? So we can just migrate now to avoid this clash?

**Comment by xbarra** [comment]
@joemoorhouse @ModeSevenIndustrialSolutions 
Do you want me to do the move to ruff?

**Comment by joemoorhouse** [comment]
Hi @xbarra, yes please - let's move this to ruff also.

**Comment by ciaransweet** [comment]
Hey folks @joemoorhouse @xbarra @ModeSevenIndustrialSolutions - Happy to move to ruff entirely in this change if it makes things easier?

The ruff linter passes so I suppose it's just a case of making sure all the black/flake8 etc calls are replace with ruff invocations...

**Pull request merged**
