### PR TITLE
Add new onboarding codes

### PR DESCRIPTION
**Pull request by mvarfima**

### CODE REVIEW

**Comment by joemoorhouse** [comment]
```python
import geopandas as gpd
import matplotlib.pyplot as plt
from rasterio import features
from rasterio.enums import MergeAlg
from rasterio.plot import show
from hazard.utilities.xarray_utilities import global_crs_transform

water_stress = gpd.read_file(filename)
crs, transform = global_crs_transform(3600 * 4, 1800 * 4)
geom_values = [(geom,value) for geom, value in zip(water_stress["geometry"], water_stress["bt4038cr"])]
rasterized = features.rasterize(geom_values[:],
                                out_shape = [1800 * 4, 3600 * 4],
                                transform = transform,
                                all_touched = True,
                                fill = float("nan"),   # background value
                                merge_alg = MergeAlg.replace,
)
fig, ax = plt.subplots(1, figsize = (10, 10))
show(rasterized, ax = ax)
```

**Comment by joemoorhouse** [comment]
Hi @mvarfima, here's a snippet to show how we can use features.rasterize to speed up that part.

**Comment by mvarfima** [comment]
Hi @joemoorhouse 

that code looks pretty good. We will test it and push it to the merge branch and hopefully we can extend it to the rest of the hazards.

Manuel

**Comment by joemoorhouse** [comment]
Hi @mvarfima, the other thing that I think can help simplify is to make more use of xarrays. The idea is that we load the data up/convert to xarrays as early as possible in the process. At this point the xarray contains both data and latitudes and longitudes (plus index coordinate) which is very convenient. Then we can write simply using:

```python
target = OscZarr()
target.write(path, xa)
```
The write method takes care of ensuring that everything follows the right standard by using:
xarray_utilities.normalize_array(da)
(in the latest version in main)

You can use target = OscZarr() directly as long as OSC_S3_ACCESS_KEY_DEV, OSC_S3_SECRET_KEY_DEV are set as environment variables. It will write directly to hazard/hazard.zarr, but I think that is fine in dev as long as we choose the right path for the data.

**Comment by joemoorhouse** [comment]
Hi @mvarfima,

I added a couple of utility routines and a test (maybe not quite a full test yet!) in the PR:
https://github.com/os-climate/hazard/pull/21

**Pull request closed without merging**
