### PR TITLE
Allow for an extra output zarr that is xarray complliant to be created

### PR DESCRIPTION
**Pull request by emileten**
Solves https://github.com/os-climate/hazard/issues/67

This adds an option to the API to create, on top of the 'raw' zarr store, an extra zarr store with coordinate labels saved so that we have something to read with native xarray functions.

This is optional, the default behavior is the legacy behavior. 

@joemoorhouse can you take a look at this ? Thank you.

### CODE REVIEW

**Comment by joemoorhouse** [comment]
Hi @emileten,
The principle of supporting both forms of array is a good one I think. I wonder if it might be neater to split this into two classes instead, that each implement `WriteDataArray` protocol (I know I have `to_zarr` elements in `OscZarr`, but that is probably a mistake)? The other class could be `OscZarrXarray` for example. The idea is that all onboarding / model classes do not care what the target is as long as it implements the protocol - up to whomever is calling it to provide the instance. We can then use the two classes to transform one to another if needed?

Thanks,
Joe

**Comment by emileten** [comment]
@joemoorhouse 

I think that's a good idea, I'm using my implementation for now as it achieves the purpose i want, and once i get time i can do what you described. 

Just to clarify, can you confirm that you're talking about having the following : 

- one new base class like : 

```
OscZarr(object)

  ... implement all common methods here ...
```

- one new `OscStandardZarr` class 

```
OscStandardZarr(OscZarr, ReadWriteDataArray):

   ... implement read/write for standard zarr, the OS-C legacy way...
```

- and one new `OscXarrayZarr` class



```
OscXarrayZarr(OscZarr, ReadWriteDataArray):

   ... implement read/write for xarray-compliant zarr ...
```

**Comment by joemoorhouse** [comment]
Hi @emileten,

Yes indeed -- or just have OscZarr and then override some parts in OscXarrayZarr as an alternative. Or have OscZarrBase and derived OscZarr and OscXarrayZarr maybe. 

Thanks,
Joe

**Comment by emileten** [comment]
@joemoorhouse apologies it wasn't my intent to merge initially but my branching workflow was becoming convoluted so I figured I would rather merge this for now, because it doesn't contain any breaking change, and make the improvement you mentioned a bit later.

**Pull request merged**
